Improve directories.

diff --git a/run-all-proxy-based-completeness b/run-all-proxy-based-completeness
--- a/run-all-proxy-based-completeness
+++ b/run-all-proxy-based-completeness
@@ -10,13 +10,38 @@
 #   You should specify a file name, such as resultXX.csv
 #   This will be the input of top level, and collection level aggregations
 
-OUTPUT_FILE=$1
-SKIP_FLAG=$2
-EXTFIELD_EXTRACTION_FLAG=$3
-VERSION=$4
 
 SECONDS=0
 JAR_VERSION=0.6-SNAPSHOT
+
+OUTPUT_FILE=
+SKIP_FLAG=0
+EXTENDED_FIELD_EXTRACTION=
+VERSION=
+
+# read the options
+TEMP=`getopt -o o:sev: --long output-file:,skip-flag,extended-field-extraction,version: -n 'test.sh' -- "$@"`
+eval set -- "$TEMP"
+
+# extract options and their arguments into variables.
+while true ; do
+    case "$1" in
+        -o|--output-file)
+            case "$2" in
+                "") shift 2 ;;
+                *) OUTPUT_FILE=$2 ; shift 2 ;;
+            esac ;;
+        -s|--skip-flag) SKIP_FLAG=1 ; shift ;;
+        -e|--extended-field-extraction) EXTENDED_FIELD_EXTRACTION=--extendedFieldExtraction ; shift ;;
+        -v|--version)
+            case "$2" in
+                "") shift 2 ;;
+                *) VERSION=$2 ; shift 2 ;;
+            esac ;;
+        --) shift ; break ;;
+        *) echo "Internal error!" ; exit 1 ;;
+    esac
+done
 
 if [[ ("$#" -ne 1 && "$#" -ne 2 && "$#" -ne 3 && "$#" -ne 4) || ("${OUTPUT_FILE}" == "") ]]; then
   echo "You should add an output file (such as resultXX.csv)!"
