Improve directories.

diff --git a/scripts/record-processing/run-all-multilingual-saturation b/scripts/record-processing/run-all-multilingual-saturation
--- a/scripts/record-processing/run-all-multilingual-saturation
+++ b/scripts/record-processing/run-all-multilingual-saturation
@@ -8,19 +8,45 @@
 #   You should specify a file name, such as resultXX-language.csv
 #   This will be the input of top level, and collection level aggregations
 
-OUTPUT_FILE=$1
-SKIP_ENRICHMENTS_FLAG=$2
-EXTFIELD_EXTRACTION_FLAG=$3
-VERSION=$4
-
 SECONDS=0
 JAR_VERSION=0.6-SNAPSHOT
 HDFS=hdfs://localhost:54310
 HEADER_FILE=header-multilingual-saturation.csv
 
+OUTPUT_FILE=
+SKIP_ENRICHMENTS_FLAG=
+EXTFIELD_EXTRACTION_FLAG=
+VERSION=
+
+
 USE_HDFS=0
 
-if [[ ("$#" -ne 1 && "$#" -ne 2 && "$#" -ne 3 && "$#" -ne 4) || ("${OUTPUT_FILE}" == "") ]]; then
+# read the options
+TEMP=`getopt -o o:sev: --long output-file:,skip-flag,extended-field-extraction,version: -n 'test.sh' -- "$@"`
+eval set -- "$TEMP"
+
+# extract options and their arguments into variables.
+while true ; do
+    case "$1" in
+        -o|--output-file)
+            case "$2" in
+                "") shift 2 ;;
+                *) OUTPUT_FILE=$2 ; shift 2 ;;
+            esac ;;
+        -s|--skip-flag) SKIP_ENRICHMENTS_FLAG=--skipEnrichments ; shift ;;
+        -e|--extended-field-extraction) EXTENDED_FIELD_EXTRACTION=--extendedFieldExtraction ; shift ;;
+        -v|--version)
+            case "$2" in
+                "") shift 2 ;;
+                *) VERSION=$2 ; shift 2 ;;
+            esac ;;
+        --) shift ; break ;;
+        *) echo "Internal error!" ; exit 1 ;;
+    esac
+done
+
+
+if [[ ("${OUTPUT_FILE}" == "") ]]; then
   echo "You should add an output file (such as resultXX-multilingual-saturation.csv)!"
   exit 1
 fi
@@ -28,14 +54,6 @@ fi
 if [ -e ${OUTPUT_FILE} ]; then
   echo "WARNING! ${OUTPUT_FILE} exists, rename it to prevent overwriting the file!"
   exit 1
-fi
-
-if [[ ("$SKIP_ENRICHMENTS_FLAG" != "--skipEnrichments" && "$SKIP_ENRICHMENTS_FLAG" != "-s") ]]; then
-  SKIP_ENRICHMENTS_FLAG=""
-fi
-
-if [[ ("$EXTFIELD_EXTRACTION_FLAG" != "--extendedFieldExtraction") ]]; then
-  EXTFIELD_EXTRACTION_FLAG=""
 fi
 
 FORMAT="fullbean"
